services:
  node:
    image: 'learning/typescript4.5.5:local'
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
      #- dist:/usr/src/app/html/js/dist/
      #- node_modules:/usr/src/app/node_modules/
    ports:
      - '3000:3000'

volumes:
  node_modules:
    driver: local

  dist:
    driver: local
