services:
  node:
    image: 'learning/typescript4.5.5:local'
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./src:/usr/src
      - dist:/usr/src/dist/
      - node_modules:/usr/src/node_modules/
    ports:
      - '3000:3000'

volumes:
  node_modules:
    driver: local

  dist:
    driver: local
